name = "rcerrud/justvalidators"
version = "0.1.1"
license = "Apache-2.0"
description = "Aiken contracts for project 'rcerrud/justvalidators'"

[repository]
user = "rcerrud"
project = "justvalidators"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "2a6df1220e0d180eb36cfe4e4265a2d47c5b83cb"
source = "github"
